# include:
#   - remote: https://gitlab.com/gitlab-org/security-products/ci-templates/raw/master/includes-dev/analyzer.yml

# print-tmp-image:
#   stage: test
#   rules:
#     - when: always
#   script: |
#     echo "$TMP_IMAGE$IMAGE_TAG_SUFFIX"

variables:
  SECURE_ANALYZERS_PREFIX: registry.gitlab.com/security-products

verify-fips:
  tags:
    - fips
  rules:
    - when: always
  stage: test
  variables:
    SAST_ANALYZER_IMAGE_TAG: "3-fips"
    SAST_ANALYZER_IMAGE: "$SECURE_ANALYZERS_PREFIX/semgrep:$SAST_ANALYZER_IMAGE_TAG"
  script:
  - "echo 'hello world'"
  - "cat /proc/sys/crypto/fips_enabled"
  - "echo '------'"
  image:
    name: "$SAST_ANALYZER_IMAGE"
