include:
  - remote: https://gitlab.com/gitlab-org/security-products/ci-templates/raw/master/includes-dev/analyzer.yml

print-tmp-image:
  stage: test
  rules:
    - when: always
  script: |
    echo "$TMP_IMAGE$IMAGE_TAG_SUFFIX"

verify-fips:
  rules:
    - when: always
  stage: test
  variables:
    SAST_ANALYZER_IMAGE_TAG: "3.1.1-fips"
    SAST_ANALYZER_IMAGE: "$SECURE_ANALYZERS_PREFIX/semgrep:$SAST_ANALYZER_IMAGE_TAG"
  script:
  - "echo 'hello world'"
  extends: ".sast-analyzer"
  allow_failure: true
  image:
    name: "$SAST_ANALYZER_IMAGE"
