variables:
  REPORT_FILENAME: gl-sast-report.json
  MAJOR: 0
  MAX_IMAGE_SIZE_BYTE: 98000000
  SAST_DEFAULT_ANALYZERS: "gosec"

include:
  - https://gitlab.com/gitlab-org/security-products/ci-templates/raw/master/includes-dev/analyzer.yml
