variables:
  REPORT_FILENAME: gl-sast-report.json
  MAX_IMAGE_SIZE_MB: 200
  MAX_IMAGE_SIZE_MB_FIPS: 1090
  SAST_EXCLUDED_ANALYZERS: "bandit,eslint,semgrep"
  SEARCH_MAX_DEPTH: 20
  
include:
  - https://gitlab.com/gitlab-org/security-products/ci-templates/-/raw/feat/scanner-version-check/includes-dev/analyzer.yml





