variables:
  REPORT_FILENAME: gl-sast-report.json
  MAX_IMAGE_SIZE_MB: 200
  MAX_IMAGE_SIZE_MB_FIPS: 1090
  SAST_EXCLUDED_ANALYZERS: "bandit,eslint,semgrep"
  SEARCH_MAX_DEPTH: 20

check scanner version:
  stage: test
  image: docker:20.10
  rules:
    - if: '$REPORT_FILENAME == "gl-sast-report.json"'
  script:
    - |
      SCANNER_VERSION=$(egrep -o "SCANNER_VERSION[:=|\:\-]{1,}([a-zA-Z0-9\.\-\_]{1,})" Dockerfile)
      SCANNER_VERSION_FIPS=$(egrep -o "SCANNER_VERSION[:=|\:\-]{1,}([a-zA-Z0-9\.\-\_]{1,})" Dockerfile.fips)
      # check if SCANNER_VERSION is the same as SCANNER_VERSION_FIPS
      if [ "$SCANNER_VERSION" != "$SCANNER_VERSION_FIPS" ]; then
        echo "Error: SCANNER_VERSION and SCANNER_VERSION_FIPS are not the same."
        exit 1
      fi
