# When updating version make sure to check on semgrepignore file as well
ARG SCANNER_VERSION=0.121.2
ARG POST_ANALYZER_SCRIPTS_VERSION=0.0.5
ARG TRACKING_CALCULATOR_VERSION=2.2.6

FROM registry.gitlab.com/security-products/post-analyzers/scripts:${POST_ANALYZER_SCRIPTS_VERSION} AS scripts
FROM registry.gitlab.com/security-products/post-analyzers/tracking-calculator:${TRACKING_CALCULATOR_VERSION} AS tracking

FROM registry.gitlab.com/gitlab-org/gitlab-runner/go-fips:1.18 AS build

ENV CGO_ENABLED=0 GOOS=linux

WORKDIR /go/src/buildapp
COPY . .

# variable to the most recent version from the CHANGELOG.md file
RUN CHANGELOG_VERSION=$(grep -m 1 '^## v.*$' "CHANGELOG.md" | sed 's/## v//') && \
        PATH_TO_MODULE=`go list -m` && \
        go build -ldflags="-X '$PATH_TO_MODULE/metadata.AnalyzerVersion=$CHANGELOG_VERSION'" -o /analyzer-semgrep

FROM registry.access.redhat.com/ubi9-minimal
USER root

ARG SCANNER_VERSION
ENV SCANNER_VERSION ${SCANNER_VERSION}
ENV SEMGREP_R2C_INTERNAL_EXPLICIT_SEMGREPIGNORE "/semgrepignore"

COPY --from=build /analyzer-semgrep /analyzer-binary
COPY rules /rules
COPY semgrepignore /semgrepignore

RUN microdnf update --assumeyes --disableplugin=subscription-manager --nodocs && \
    microdnf install --assumeyes shadow-utils util-linux git wget python39 python3-pip --disableplugin=subscription-manager --nodocs && \
    \
    # Install Semgrep
    pip3 install semgrep==$SCANNER_VERSION && \
    \
    # Configure CA Certificates
    mkdir -p /etc/ssl/certs/ && \
    touch /etc/ssl/certs/ca-certificates.crt && \
    chmod g+w /etc/ssl/certs/ca-certificates.crt && \
    \
    # Create gitlab user
    useradd --create-home gitlab -g root && \
    \
    # Cleanup libs that are no longer needed
    microdnf remove --assumeyes shadow-utils && \
    microdnf clean all && \
    microdnf remove --assumeyes microdnf

COPY --from=tracking /analyzer-tracking /analyzer-tracking
COPY --from=scripts /start.sh /analyzer

USER gitlab

ENTRYPOINT []
CMD ["/analyzer", "run"]
