function baz(argOne, argTwo) {
  fs.appendFile(argOne, data, callback)
  fs.appendFileSync(argOne, data)
  fs.chmod(argOne, mode, callback)
  fs.chmodSync(argOne, mode)
  fs.chown(argOne, uid, gid, callback)
  fs.chownSync(argOne, uid, gid)
  fs.createReadStream(argOne)
  fs.createWriteStream(argOne)
  fs.exists(argOne, callback)
  fs.existsSync(argOne, callback)
  fs.lchmod(argOne, mode, callback)
  fs.lchmodSync(argOne, mode)
  fs.lchown(argOne, uid, gid, callback)
  fs.lchownSync(argOne, uid, gid)
  fs.link(argOne, argTwo, callback)
  fs.linkSync(argOne, argTwo)
  fs.lstat(argOne, callback)
  fs.lstatSync(argOne)
  fs.mkdir(argOne, callback)
  fs.mkdirSync(argOne)
  fs.open(argOne, callback)
  fs.openSync(argOne)
  fs.readdir(argOne, callback)
  fs.readdirSync(argOne)
  fs.readFile(argOne, callback)
  fs.readFileSync(argOne)
  fs.readlink(argOne, callback)
  fs.readlinkSync(argOne)
  fs.realpath(argOne, callback)
  fs.realpathSync(argOne)
  fs.rename(argOne, argTwo, callback)
  fs.renameSync(argOne, argTwo)
  fs.rmdir(argOne, callback)
  fs.rmdirSync(argOne)
  fs.stat(argOne, callback)
  fs.statSync(argOne)
  fs.symlink(argOne, argTwo, callback)
  fs.symlinkSync(argOne, argTwo)
  fs.truncate(argOne, callback)
  fs.truncateSync(argOne)
  fs.unlink(argOne, callback)
  fs.unlinkSync(argOne)
  fs.unwatchFile(argOne)
  fs.utimes(argOne, callback)
  fs.utimesSync(argOne)
  fs.watch(argOne)
  fs.watchFile(argOne, listener)
  fs.writeFile(argOne, callback)
  fs.writeFileSync(argOne)
}
