function baz(argOne, argTwo) {
  // string args
  fs.appendFile('foo', data, callback)
  fs.appendFileSync('foo', data)
  fs.chmod('foo', mode, callback)
  fs.chmodSync('foo', mode)
  fs.chown('foo', uid, gid, callback)
  fs.chownSync('foo', uid, gid)
  fs.createReadStream('foo')
  fs.createWriteStream('foo')
  fs.exists('foo', callback)
  fs.existsSync('foo', callback)
  fs.lchmod('foo', mode, callback)
  fs.lchmodSync('foo', mode)
  fs.lchown('foo', uid, gid, callback)
  fs.lchownSync('foo', uid, gid)
  fs.link('foo', 'bar', callback)
  fs.linkSync('foo', 'bar')
  fs.lstat('foo', callback)
  fs.lstatSync('foo')
  fs.mkdir('foo', callback)
  fs.mkdirSync('foo')
  fs.open('foo', callback)
  fs.openSync('foo')
  fs.readdir('foo', callback)
  fs.readdirSync('foo')
  fs.readFile('foo', callback)
  fs.readFileSync('foo')
  fs.readlink('foo', callback)
  fs.readlinkSync('foo')
  fs.realpath('foo', callback)
  fs.realpathSync('foo')
  fs.rename('foo', 'bar', callback)
  fs.renameSync('foo', 'bar')
  fs.rmdir('foo', callback)
  fs.rmdirSync('foo')
  fs.stat('foo', callback)
  fs.statSync('foo')
  fs.symlink('foo', 'bar', callback)
  fs.symlinkSync('foo', 'bar')
  fs.truncate('foo', callback)
  fs.truncateSync('foo')
  fs.unlink('foo', callback)
  fs.unlinkSync('foo')
  fs.unwatchFile('foo')
  fs.utimes('foo', callback)
  fs.utimesSync('foo')
  fs.watch('foo')
  fs.watchFile('foo', listener)
  fs.writeFile('foo', callback)
  fs.writeFileSync('foo')

  // constant string arguments
  strArgOne = 'foo'
  strArgTwo = 'bar'
  fs.appendFile(strArgOne, data, callback)
  fs.appendFileSync(strArgOne, data)
  fs.chmod(strArgOne, mode, callback)
  fs.chmodSync(strArgOne, mode)
  fs.chown(strArgOne, uid, gid, callback)
  fs.chownSync(strArgOne, uid, gid)
  fs.createReadStream(strArgOne)
  fs.createWriteStream(strArgOne)
  fs.exists(strArgOne, callback)
  fs.existsSync(strArgOne, callback)
  fs.lchmod(strArgOne, mode, callback)
  fs.lchmodSync(strArgOne, mode)
  fs.lchown(strArgOne, uid, gid, callback)
  fs.lchownSync(strArgOne, uid, gid)
  fs.link(strArgOne, strArgTwo, callback)
  fs.linkSync(strArgOne, strArgTwo)
  fs.lstat(strArgOne, callback)
  fs.lstatSync(strArgOne)
  fs.mkdir(strArgOne, callback)
  fs.mkdirSync(strArgOne)
  fs.open(strArgOne, callback)
  fs.openSync(strArgOne)
  fs.readdir(strArgOne, callback)
  fs.readdirSync(strArgOne)
  fs.readFile(strArgOne, callback)
  fs.readFileSync(strArgOne)
  fs.readlink(strArgOne, callback)
  fs.readlinkSync(strArgOne)
  fs.realpath(strArgOne, callback)
  fs.realpathSync(strArgOne)
  fs.rename(strArgOne, strArgTwo, callback)
  fs.renameSync(strArgOne, strArgTwo)
  fs.rmdir(strArgOne, callback)
  fs.rmdirSync(strArgOne)
  fs.stat(strArgOne, callback)
  fs.statSync(strArgOne)
  fs.symlink(strArgOne, strArgTwo, callback)
  fs.symlinkSync(strArgOne, strArgTwo)
  fs.truncate(strArgOne, callback)
  fs.truncateSync(strArgOne)
  fs.unlink(strArgOne, callback)
  fs.unlinkSync(strArgOne)
  fs.unwatchFile(strArgOne)
  fs.utimes(strArgOne, callback)
  fs.utimesSync(strArgOne)
  fs.watch(strArgOne)
  fs.watchFile(strArgOne, listener)
  fs.writeFile(strArgOne, callback)
  fs.writeFileSync(strArgOne)
}
